services:
  postgres:
    container_name: postgresdb
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pgdb_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - it-network  
  
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - it-network

volumes:
  pgdb_data:   

networks:
  it-network:
    driver: bridge